### ISSUE TITLE
Crash on more than single dimension values 

### ISSUE THREAD

**Issue by gkorland** [lantiga/RedisTF#18]
```
127.0.0.1:6379> TF.TENSOR gg3 FLOAT 3 1 2 2 VALUES 2 2 2 2
Error: Server closed the connection
```

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
9649:M 04 Oct 2018 18:49:35.029 # Redis 999.999.999 crashed by signal: 11
9649:M 04 Oct 2018 18:49:35.029 # Crashed running the instruction at: 0x7f4ceabf6f9a
9649:M 04 Oct 2018 18:49:35.029 # Accessing address: (nil)
9649:M 04 Oct 2018 18:49:35.029 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/guy/redislabsmodules/RedisTF/src/redistf.so(RedisTF_SetValueFromDouble+0x4c)[0x7f4ceabf6f9a]

Backtrace:
/home/guy/redislabsmodules/redis/src/redis-server *:6379(logStackTrace+0x5a)[0x557179345d9a]
/home/guy/redislabsmodules/redis/src/redis-server *:6379(sigsegvHandler+0xb1)[0x557179346551]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f4ced3fc890]
/home/guy/redislabsmodules/RedisTF/src/redistf.so(RedisTF_SetValueFromDouble+0x4c)[0x7f4ceabf6f9a]
```

**Comment by lantiga** [comment]
Solved by #19

**Comment by gkorland** [comment]
@lantiga #19 didn't solve the crash I'm still getting it, the crash happens after it passes the fix in #19

**Comment by lantiga** [comment]
@gkorland after @19 I get 
```
127.0.0.1:6379> TF.TENSOR gg3 FLOAT 3 1 2 2 VALUES 2 2 2 2
OK
```

**Comment by lantiga** [comment]
Can you send me more details on the crash?

**Comment by gkorland** [comment]
I'm getting the crash at the top, when the code trying to call TF method to extract the underline array from the Tensor

**Comment by lantiga** [comment]
This works for me
```
TF.TENSOR gg3 FLOAT 3 1 2 2 VALUES 2 2 2 2
TF.VALUES gg3
```

Can you please try to pull from master, rebuild and try again? Thanks!

**Comment by gkorland** [comment]
Same crash

```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
25475:M 05 Oct 2018 15:00:29.890 # Redis 999.999.999 crashed by signal: 11
25475:M 05 Oct 2018 15:00:29.890 # Crashed running the instruction at: 0x7fb4237f6f0a
25475:M 05 Oct 2018 15:00:29.890 # Accessing address: (nil)
25475:M 05 Oct 2018 15:00:29.890 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/guy/redislabsmodules/RedisTF/src/redistf.so(RedisTF_SetValueFromDouble+0x4c)[0x7fb4237f6f0a]

Backtrace:
/home/guy/redislabsmodules/redis/src/redis-server *:6379(logStackTrace+0x5a)[0x563dad052d9a]
/home/guy/redislabsmodules/redis/src/redis-server *:6379(sigsegvHandler+0xb1)[0x563dad053551]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fb425ed5890]
/home/guy/redislabsmodules/RedisTF/src/redistf.so(RedisTF_SetValueFromDouble+0x4c)[0x7fb4237f6f0a]

```

**Comment by lantiga** [comment]
Ah! Ok, can we stay on Redis 5.0 for today?
